0,'Lifestyle','Bringing the outdoors in is a key philosophy of Hygge'
1,'Lifestyle','Using Candlelight in the evenings warms a home' 
2,'Lifestyle','Avoid cluttering your work and home environment' 
3,'Lifestyle','Lighting the fire in the hearth distinguishes a house from a home' 
4,'Lifestyle','Sharing meals brings a warmth to the good food');
5,'Lifestyle','Making hot tea and coffee is a pleasure in itself' 
6,'Lifestyle','Surround yourself with objects that tell a story' 
7,'Lifestyle','Soft furnishings send out a cozy atmosphere' 
8,'Inspire','If you want to achieve greatness stop asking for permission' 
9,'Inspire','It does not matter how slowly you go as long as you do not stop' 
10,'Inspire','Find out what you are doing best and get someone to pay you for doing it' 
11,'Inspire','The future belongs to those who believe in the beauty of their dreams' 
12,'Inspire','Everything I let go of has claw marks on it' 
13,'Inspire','If you are offered a seat on a rocketship - don''t ask which seat? Just get on' 
14,'Inspire','We mature with the damage not with the years' 
15,'Inspire','Every day is a new beginning - smile and start again' 
16,'Inspire','Better to be slapped with the truth than kissed with a lie' 
17,'Inspire','Not everyone with a map knows where they are going' 
18,'Health','Eat more mindfully' 
19,'Health','Don’t skip breakfast' 
20,'Health','Choose lean protein sources such as fish or poultry or tofu' 
21,'Health','Avoid processed foods' 
22,'Health','Try a mediterranean diet plan' 
23,'Health','Drink water to avoid getting thirsty' 
24,'Health','Cut down on sugar and your glucose tolerance will diminish' 
25,'Health','Reduce your salt intake' 
26,'Health','Avoid overeating and snacking' 
27,'Health','Eat more crunchy foods' 
28,'Active','Take a real lunch break from your desk' 
29,'Active','Bike or walk to work' 
30,'Active','Try interval training in your exercise plan' 
31,'Active','Park farther away from your destination' 
32,'Active','Choose the stairs over the elevator' 
33,'Active','Clean the house' 
34,'Active','Exercise your mind' 
35,'Active','Try a new outdoor activity' 
36,'Active','Buddy up and make exercise a group activity' 
37,'Active','Set activity goals' 
38,'Humour','6:30 is the best time on a clock... ...hands down.' 
39,'Humour','A man walked into a doctor''s office . . . He said to the doctor: I''ve hurt my arm in several places. The doctor said: Well don''t go there any more.' 
40,'Humour','A stamp collector walks into a bar... He walks up to the hostess and says You''re more beautiful than any stamp in my collection She replied Philately will get you nowhere.'
41,'Humour','Actually there are but two types of people Those who can extrapolate from limited data ...'
42,'Humour','Breaking news! Energizer Bunny arrested... ...charged with battery.' 
43,'Humour','Broken pencils... ...are pointless.' 
44,'Humour','Broom advocates for cleaner work environment.' 
45,'Humour','Did you hear about the butcher who backed into the meat grinder? He got a little behind in his work.' 
46,'Humour','Did you hear about the Italian chef that died? He pasta way.' 
47,'Humour','Did you hear about the lawyer for U2? He was Pro-Bono' 
48,'Humour','Did you hear about the mathematician who hated negative numbers? He''ll stop at nothing to avoid them!' 
49,'Humour','Don''t you hate jokes about German sausage? They''re the wurst!' 
50,'Humour','Every single morning I get hit by the same bike... It''s a vicious cycle.' 
51,'Humour','Have you heard about the 2 Spanish firemen? Jose and hose B' 
52,'Humour','Have you heard what I think of windmills? Big Fan.' 
53,'Humour','How did the desk lamp store manager feel when thieves stole all his lightbulbs? He was delighted.' 
54,'Humour','I can't stand Russian Dolls... They''re always so full of themselves!'
55,'Humour','I farted on an elevator, it was wrong on so many levels.' 
56,'Humour','I fear for the calendar... ...its days are numbered.' 
57,'Humour','I like camping but... it''s so in tents' 
58,'Humour','I never buy Velcro It''s such a rip off.' 
59,'Humour','I think I want a job cleaning mirrors... ...it''s just something I can see myself doing.' 
60,'Humour','If life gives you melons - you might have dyslexia.'
61,'Humour','I'm making a band! I started a band called 999 Megabytes...we haven''t gotten a gig yet.'
62,'Humour','One fifth of people... ...are just too tense!' 
63,'Humour','There are two types of people in this world 1. Those who can extrapolate from incomplete data' 
64,'Humour','Today I'm 45. But with the wind chill I feel like 32.'
65,'Humour','What did the green grape say to the purple grape? - 'Breathe, stupid!'
66,'Humour','What do Engineers use as birth control? Their Personality.' 
67,'Humour','What do you call a woman with one leg? Eileen' 
68,'Humour','What's the difference between a fish and a guitar? You can''t tuna fish!'
69,'Humour','Who invented fractions? Henry the 1/8' 
70,'Humour','Why are pirates so mean? I dont know, they just arrrrrrrrr!' 
71,'Humour','Why was 9 afraid of 20? 28 29''s' 
72,'Humour','Why was the burrito embarrassed? It saw the salad dressing.' 
73,'Humour','You can pick your friends and you can pick your nose... But you can't pick your friend''s nose'
74,'Humour','You can tune a guitar... but you can''t tuna fish!' 
75,'Humour','You know what I hate about fashion designers? They are so clothes-minded.' 
76,'Humour','You know what's the problem with Mexican and black jokes? If you've heard Juan, you've heard Jamaal.'
77,'Humour','You know why ancient Greek children were always getting lost from their parents? Cause they kept Roman around!' 
78,'Humour','Why do Java developers wear glasses? Because they don't C#'
79,'Rugby','Ireland have played Argentina 18 times and won 12' 
80,'Rugby','Australia played Ireland 36 times an lost only 13' 
81,'Rugby','Ireland have drawn against England a record-breaking 8 times out of 134 matches played' 
82,'Rugby','Ireland have scored a record breaking 1547 points against Scotland' 
83,'Rugby','Ireland have never lost a Rugby match to the USA Tonga or Zimbabwe' 
84,'Rugby','Ireland have conceded the most trys against New Zealand 113 versus 39' 
85,'Rugby','Romania conceded 49 Irish try's in only 9 matches'
86,'Rugby','Ireland have an unbeaten record in Russia Fiji and Japan' 
87,'Rugby','France and Wales have drawn against Ireland the most number of times' 
88,'Rugby','France Wales Scotland England Italy play against Ireland in the Six Nations' 
89,'Rugby','Ireland only missed out on winning once against Canada and Samoa' 
90,'Soccer','Liverpool scored a record 24 away goals last season and 4 against Bournemouth' 
91,'Soccer','Chelsea scored 21 away goals this season and 4 against Burnley' 
92,'Soccer','Man. United comitted 174 fouls or just 6% of the league total this year' 
93,'Soccer','Man. United score a goal and a half for every goal conceded at home games' 
94,'Soccer','Liverpool scored 6.7 goals for every goal conceded at home games' 
95,'Soccer','Liverpool received 50% at home games of the yellow cards their oponents received' 
96,'Soccer','Chelsea were never losing at half time at home games in 2018' 
97,'Soccer','There were 24 red card given to away teams and only 15 to home teams this season' 
98,'Soccer','There are near equal odds of a match being a draw at half time to a one side advantage' 
99,'Soccer','There were 32 away game hattricks scored this season by all teams' 
100,'Friend','You''re my best friend.' 
101,'Friend','We are peas in a pod.' 
102,'Friend','We are two bits in a byte.' 
103,'Friend','We are getting along famously.' 
104,'Friend','We are moving in the same circles now.' 
105,'Friend','I think we are hitting it off.' 
106,'Friend','We know each other inside out.' 
107,'Friend','We are a good match.' 
108,'Friend','I don't exist without you.'
109,'Friend','I'll be there for you even when the rain starts to pour.'
110,'Friend','When it hasn't been your day I''ll be there for you.')
111,'Question','What's on your bucket list?'
112,'Question','What do you do? and how long have you been doing it?' 
113,'Question','What are you doing today?' 
114,'Question','Do you believe in ghosts?' 
115,'Question','How did you meet your best friend?' 
116,'Question','Do you have a sweet tooth?' 
117,'Question','What would make your day, today?' 
118,'Question','Name one thing you are better at than your friend?' 
119,'Question','I sense a journey in your future, where would you be headed?' 
120,'Question','Would you take a break and have a cup of tea?' 
121,'Inspire', 'Though my soul may set in darkness it will rise in perfect light I have loved the stars too fondly to be fearful of the night'