1,Alternative,'What is new?','au revoir'
2,Competition,'How are you doing?','Goodbye'
3,Compliment,'How is your day going?','So long'
4,Recurring,'Nice to see you again so soon!','See you later alligator!'
5,Sated,'Please to meet you','Have a nice day'
6,Unlimited,'Hi','Catch you later'
7,Urgent,'What is up Doc?','Safe home'